### ISSUE TITLE
PenRadioButton does not understand "label:"

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Penfeld#4]
Hi Penfeld Team ;-)

When bloc widgets sample execution (PenBlocWidgetsSample(Class)>>open) an exception is raised in PenBlocWidgetsSample>>radioButton:

PenRadioButton does not understand "label:".

Pen
I suggest to correct with "text:".

Thks!

**Comment by nolwennfournier** [comment]
Example corrected.
Thanks for having reported it!
